# .github/workflows/main.yml
name: Execute Main Pipeline

on:
  workflow_dispatch:

jobs:
  development_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run My Shortcut Setup
        uses: ./.github/actions/my-setup-actions
        with:
          worker_name: "DevTeam-Runner"

      - name: Run Core Code
        run: echo "Doing core work inside the prepped workspace..."