name : output_jobs_moving

on:
  workflow_dispatch:

jobs:
  job1:
   runs-on: ubuntu-latest
   outputs:
     sum_result : {{ steps.add.outputs.result }}
   steps:
     - name: addition_job
       id : add
       shell: python
       run : |
        import os 

        num1 =4 
        num2 =3

        result = num1+num2

        print(f"result of addition is {result}")
        with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
            print(f"result={result}", file=fh)

  job2:
    runs-on: ubuntu-latest
    needs: job1          

    steps:
      - name : my_multiplication 
        env:
          result : {{ needs.job1.outputs.sum_result }}
        run : |
          echo "${result}"

